# Generated by Django 5.1.6 on 2025-02-25 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='SportActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=True)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_activities', to='App.contract')),
                ('sport_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_for_contracts', to='App.sportactivity')),
            ],
        ),
        migrations.CreateModel(
            name='SportPartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_partners', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='sport_partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='App.sportpartner'),
        ),
        migrations.CreateModel(
            name='SportProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255)),
                ('company_email', models.EmailField(max_length=254, unique=True)),
                ('company_phone', models.CharField(max_length=20)),
                ('company_address', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_providers', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='sportactivity',
            name='sport_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_activities', to='App.sportprovider'),
        ),
        migrations.AddField(
            model_name='contract',
            name='sport_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='App.sportprovider'),
        ),
        migrations.CreateModel(
            name='SportWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('sport_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_works', to='App.sportpartner')),
            ],
        ),
        migrations.CreateModel(
            name='SportCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True)),
                ('sport_worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sport_codes', to='App.sportworker')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField(auto_now_add=True)),
                ('activity_time', models.TimeField(auto_now_add=True)),
                ('sport_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='App.sportactivity')),
                ('sport_partner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='App.sportpartner')),
                ('sport_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='App.sportprovider')),
                ('sport_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='App.sportworker')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='contract',
            unique_together={('sport_provider', 'sport_partner', 'start_date')},
        ),
    ]
